#!/usr/bin/env python3
"""
png/shihou_cource_unity.png から外周コースの 3 本線 (外側境界 / 中央線 / 内側境界) を抽出し,
Web シミュレータの「理想検出」モード用データ js/course_lines.js を生成する.

    python3 web_simulator/tools/extract_course_lines.py

コース画像の中心付近から放射状にレイを飛ばし, 外側から内側へ白線の横断位置を拾う:
    1, 2 本目 = 外側の二重線 (2 本目がレーン境界), 以降は 2 本目からの距離で
    中央線 (2.3-3.9m) / 内側境界 (5.0-7.6m) を判定. 破線の切れ目・合流部は null (線なし).
座標変換は js/simulator.js の COURSE_POSE / course.js の COURSE_WIDTH_M と同じ.
"""
import json
import os

import cv2
import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
IMG = os.path.join(HERE, "..", "png", "shihou_cource_unity.png")
OUT = os.path.join(HERE, "..", "js", "course_lines.js")

COURSE_WIDTH_M = 100.0                 # course.js
COURSE_POSE = (13.22, 35.41)           # simulator.js COURSE_POSE (yaw = pi/2)
RAY_CENTER = (495, 406)                # 外周ループの内側にある画像座標
N_RAYS = 1440


def main():
    im = cv2.imread(IMG)
    g = cv2.cvtColor(im, cv2.COLOR_BGR2GRAY)
    H, W = g.shape
    depth_m = COURSE_WIDTH_M * H / W
    mpp = COURSE_WIDTH_M / W
    white = g > 195
    cx, cy = RAY_CENTER

    def to_world(px, py):
        lx = (px / W - 0.5) * COURSE_WIDTH_M
        ly = (0.5 - py / H) * depth_m
        return round(COURSE_POSE[0] - ly, 3), round(COURSE_POSE[1] + lx, 3)

    lines = {"outer": [], "center": [], "inner": []}
    for k in range(N_RAYS):
        th = 2 * np.pi * k / N_RAYS
        dx, dy = np.cos(th), np.sin(th)
        rs = np.arange(560, 120, -0.5)
        xs = (cx + rs * dx).round().astype(int)
        ys = (cy + rs * dy).round().astype(int)
        ok = (xs >= 0) & (xs < W) & (ys >= 0) & (ys < H)
        vals = np.zeros(len(rs), bool)
        vals[ok] = white[ys[ok], xs[ok]]
        runs, i = [], 0
        while i < len(vals):
            if vals[i]:
                j = i
                while j < len(vals) and vals[j]:
                    j += 1
                runs.append(rs[(i + j - 1) // 2])
                i = j
            else:
                i += 1
        o = c = n = None
        if len(runs) >= 2 and runs[0] - runs[1] < 12:
            o = runs[1]
            for r in runs[2:]:
                d = (o - r) * mpp
                if 2.3 < d < 3.9 and c is None:
                    c = r
                elif 5.0 < d < 7.6 and n is None:
                    n = r
        for name, r in (("outer", o), ("center", c), ("inner", n)):
            lines[name].append(None if r is None else list(to_world(cx + r * dx, cy + r * dy)))

    with open(OUT, "w") as f:
        f.write("// Generated by web_simulator/tools/extract_course_lines.py -- do not edit.\n")
        f.write("// Outer-loop white lines of png/shihou_cource_unity.png in world (ROS) coordinates,\n")
        f.write("// sampled by rays around the loop (null = no line there: dashes / junctions).\n")
        f.write("export const COURSE_LINES = ")
        json.dump(lines, f, separators=(",", ":"))
        f.write(";\n")
    print("wrote", OUT)


if __name__ == "__main__":
    main()
