// In-browser port of oit_navigation's lane_detector UFLD backend (UFLD v1).
// Runs web_simulator/models/ufld.onnx (generated by
// `ros2 run oit_navigation export_ufld_onnx`, see
// src/oit_navigation/oit_navigation/export_ufld_onnx.py) through
// onnxruntime-web, then decodes the row-anchor classification output exactly
// like src/oit_navigation/oit_navigation/ufld/model.py decode_lanes().
//
// Preprocessing matches UFLDLaneModel.preprocess(): the whole frame is
// resized to 800x288, RGB, ImageNet mean/std.

const NORM_MEAN = [0.485, 0.456, 0.406]; // R, G, B
const NORM_STD = [0.229, 0.224, 0.225];

export class UfldLaneDetector {
  constructor() {
    this.session = null;
    this.meta = null;
    this._canvas = document.createElement('canvas');
    this._ctx = null;
  }

  async load(onnxUrl, metaUrl, wasmDir) {
    const res = await fetch(metaUrl);
    if (!res.ok) {
      throw new Error(`${metaUrl} not found -- run \`ros2 run oit_navigation export_ufld_onnx\` first`);
    }
    this.meta = await res.json();
    this._canvas.width = this.meta.input_w;
    this._canvas.height = this.meta.input_h;
    this._ctx = this._canvas.getContext('2d', { willReadFrequently: true });

    // eslint-disable-next-line no-undef -- global UMD export (index.html <script>)
    ort.env.wasm.wasmPaths = new URL(wasmDir, document.baseURI).href;
    try {
      this.session = await ort.InferenceSession.create(onnxUrl, {
        executionProviders: ['webgpu'],
        graphOptimizationLevel: 'all',
      });
    } catch (err) {
      console.warn('WebGPU EP unavailable, falling back to CPU WASM inference', err);
      this.session = await ort.InferenceSession.create(onnxUrl, {
        executionProviders: ['wasm'],
        graphOptimizationLevel: 'all',
      });
    }
  }

  /**
   * @returns {Promise<Array<null|{u:number[], v:number[], conf:number[]}>>}
   *   one entry per UFLD lane slot, image-pixel coordinates of sourceCanvas,
   *   sorted top -> bottom (same as decode_lanes()).
   */
  async detect(sourceCanvas, minPoints = 3) {
    if (!this.session) throw new Error('UfldLaneDetector.load() must complete before detect()');
    const { input_w: W, input_h: H } = this.meta;
    this._ctx.drawImage(sourceCanvas, 0, 0, sourceCanvas.width, sourceCanvas.height, 0, 0, W, H);
    const { data } = this._ctx.getImageData(0, 0, W, H);
    const plane = W * H;
    const input = new Float32Array(3 * plane);
    for (let i = 0; i < plane; i++) {
      input[i] = (data[i * 4] / 255 - NORM_MEAN[0]) / NORM_STD[0];
      input[plane + i] = (data[i * 4 + 1] / 255 - NORM_MEAN[1]) / NORM_STD[1];
      input[2 * plane + i] = (data[i * 4 + 2] / 255 - NORM_MEAN[2]) / NORM_STD[2];
    }
    // eslint-disable-next-line no-undef
    const tensor = new ort.Tensor('float32', input, [1, 3, H, W]);
    const results = await this.session.run({ input: tensor });
    return decodeLanes(results.output.data, this.meta, sourceCanvas.width, sourceCanvas.height, minPoints);
  }
}

// Port of ufld/model.py decode_lanes(). `out` is the flat [G+1, R, L] logits.
export function decodeLanes(out, meta, imgW, imgH, minPoints = 3) {
  const G = meta.griding_num;
  const R = meta.cls_num_per_lane;
  const L = meta.num_lanes;
  const at = (g, r, l) => out[(g * R + r) * L + l];
  const colSampleW = (meta.input_w - 1) / (G - 1);

  const lanes = [];
  for (let l = 0; l < L; l++) {
    const us = [];
    const vs = [];
    const confs = [];
    for (let r = 0; r < R; r++) {
      let maxLogit = -Infinity;
      let argmax = 0;
      for (let g = 0; g <= G; g++) {
        const x = at(g, r, l);
        if (x > maxLogit) { maxLogit = x; argmax = g; }
      }
      if (argmax === G) continue; // "no lane on this row"
      let sumAll = 0;
      let sumCells = 0;
      let weighted = 0;
      for (let g = 0; g <= G; g++) {
        const e = Math.exp(at(g, r, l) - maxLogit);
        sumAll += e;
        if (g < G) { sumCells += e; weighted += e * (g + 1); }
      }
      const loc = weighted / Math.max(sumCells, 1e-9);
      us.push((loc * colSampleW * imgW) / meta.input_w - 1);
      vs.push((meta.row_anchor[r] * imgH) / meta.input_h - 1);
      confs.push(1 / sumAll); // max prob = exp(0) / sumAll
    }
    lanes.push(us.length >= minPoints ? { u: us, v: vs, conf: confs } : null);
  }
  return lanes;
}
